name: Deploy

on:
  pull_request:
    branches: [ main ]


jobs:
  deploy:
    # if the branch name of the PR does not contain 'skip-deploy'
    if: "!contains(github.head_ref, 'skip-deploy')"
    runs-on: ubuntu-latest
    steps:
    - id: deploy
      uses: bitovi/github-actions-deploy-docker-to-ec2@add-public-dns-config
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS_TRAINING}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS_TRAINING}}
        aws_default_region: us-east-1
        dot_env: ${{ secrets.DOT_ENV }}

        app_port: 3000