name: Destroy

on:
  workflow_dispatch:
    inputs:
      aws_resource_identifier:
        description: Resource Identifier for deployed resources
  pull_request:
    types: [ closed ]


jobs:
  destroy:
    # if the branch name of the PR does not contain 'skip-deploy'
    if: "!contains(github.head_ref, 'skip-deploy')"
    runs-on: ubuntu-latest
    steps:
    - id: destroy
      uses: bitovi/github-actions-deploy-docker-to-ec2@add-public-dns-config
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_DEVOPS_TRAINING}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEVOPS_TRAINING}}
        aws_default_region: us-east-1
        stack_destroy: "true"
        dot_env: ${{ secrets.DOT_ENV }}
        aws_resource_identifier: ${{ github.event.inputs.aws_resource_identifier }}
        app_port: 3000